name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Lint project
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠 Build project
        run: pnpm build

      - name: 🧪 Playground Unit Test
        run: pnpm -C playground run test:unit --coverage

      - name: 🧪 Playground Nuxt Test
        run: pnpm -C playground run test:nuxt --coverage

      - name: 🟩 Coverage
        uses: codecov/codecov-action@v3
        with:
          files: playground/coverage/nuxt/cover.xml,playground/coverage/unit/cover.xml
